### ISSUE TITLE
Dane: przemyśleć czy EWD

### ISSUE THREAD

**Issue by mihal277** [mihal277/DataProducts#8]

**Comment by martarozek** [comment]
"Wskaźniki EWD są więc miarami relatywnymi. Nie pokazują, jak bardzo uczniowie „zmądrzeli” bądź „zgłupieli” w danej szkole, ani tego, jak dużo się nauczyli. Natomiast pozwalają zobaczyć, czy szkoła naucza mniej, czy bardziej efektywnie, niż przeciętna placówka w kraju."

Czy to jest to co nas interesuje? Bo w sumie dla takiego włodarza gminnego to jest ważne czy szkoła dobrze uczy, a nie czy są wyniki wysokie (chyba że chodzi mu o prestiż a nie poprawę poziomu swoich szkół...).

**Comment by martarozek** [comment]
http://zpd.ibe.edu.pl/doku.php?id=r_zmienne&zm=wartosciWskaznikow

To wygląda bardzo dobrze według mnie, więc ściągałabym tylko EWD teraz.
